### ISSUE TITLE
Trying to run quickstart example, got error The 'realm_access' section of the provided access token is missing on /admin method

### ISSUE THREAD

**Issue by Felix-neko** [code-specialist/fastapi-keycloak#82]
Hi again!

I've installed fastapi-keycloak 1.0.7 from PyPi and tried to run basic example.

I've started keycloak with docker-compose, created a user and got access token.

I've tried to run /admin method from Postman (with `Authorization` token `Bearer {access_token}`).

Alas, it gave me the following internal server error:

```
INFO:     127.0.0.1:54016 - "GET /admin HTTP/1.1" 500 Internal Server Error
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/uvicorn/protocols/http/h11_impl.py", line 407, in run_asgi
    result = await app(  # type: ignore[func-returns-value]
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/uvicorn/middleware/proxy_headers.py", line 78, in __call__
    return await self.app(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi/applications.py", line 270, in __call__
    await super().__call__(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/applications.py", line 124, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 184, in __call__
    raise exc
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/middleware/errors.py", line 162, in __call__
    await self.app(scope, receive, _send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 79, in __call__
    raise exc
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/middleware/exceptions.py", line 68, in __call__
    await self.app(scope, receive, sender)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/routing.py", line 706, in __call__
    await route.handle(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/routing.py", line 276, in handle
    await self.app(scope, receive, send)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/routing.py", line 66, in app
    response = await func(request)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi/routing.py", line 225, in app
    solved_result = await solve_dependencies(
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi/dependencies/utils.py", line 535, in solve_dependencies
    solved = await run_in_threadpool(call, **sub_values)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/starlette/concurrency.py", line 41, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/anyio/to_thread.py", line 31, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 937, in run_sync_in_worker_thread
    return await future
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/anyio/_backends/_asyncio.py", line 867, in run
    result = context.run(func, *args)
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi_keycloak/api.py", line 264, in current_user
    if role not in user.roles:
  File "/mnt/dump1/Projects/fastapi_sandbox/venv_py3.8/lib/python3.8/site-packages/fastapi_keycloak/model.py", line 122, in roles
    raise KeycloakError(
fastapi_keycloak.exceptions.KeycloakError: HTTP 404: The 'realm_access' section of the provided access token is missing
```

Here's the exact code I'm running: https://github.com/Felix-neko/fastapi_sandbox/tree/main/fastapi_sandbox

Can you please tell me: how can it be fixed?

**Comment by Felix-neko** [comment]
UPD: I've read the next paragraph of docs after Quickstart: https://fastapi-keycloak.code-specialist.com/keycloak_configuration/

When I enabled client's Full Scope, it helped.

Maybe you can place the keycloak configuration topic before Quickstart for such guys like me?

**Comment by DamScan** [comment]
I had this same problem. I managed to get out of it the same way.
But above all I activated "Service Account Enabled" in the "Admin-cli".
I found quite a bit of info here (knowing that I didn't use the examples in the documentation)
https://www.appsdeveloperblog.com/keycloak-rest-api-create-a-new-user/
This lib is no longer maintained and seeks to be adopted, it's a shame because it looks promising.

**Comment by yannicschroeer** [comment]
Feel free to contact us and pick up the maintenance. We can not spare the time and do no longer use Keycloak due to its wide variety of deficits

**Comment by DamScan** [comment]
Why not...
But I doubt I'll be as good as your team.
It could be a good exercise for me.
What are the terms of recovery?

**Comment by ScottFred** [comment]
@yannicschroeer  Can you expand on your comment above, "no longer use Keycloak due to its wide variety of deficits"?  Would you be willing to share what Authentication Server you are now using?  (I'm considering using Keycloak as our OAuth server, but there are things that concern me about it such as over 1,900 Issues reported on GitHub and 198 Pull Requests).

**Comment by yannicschroeer** [comment]
@ScottFred I‘m not well into the topic anymore, but our main concerns were a horrible documentation and a lot of major versions as well as undocumented non-backward-compatible changes. It was simply too unstable to use. I can’t tell if it became better, but that year we used it, we had 8 new Major versions and over 15 breaking changes, making this unmaintainable with the amount of time we can spare.

**Comment by ScottFred** [comment]
@yannicschroeer Thanks for the additional detail.  Can you tell me what Authentication Server you chose to use instead?  (My experience with CentOS years ago (a RedHat ecosystem) was similar... I just wanted a stable Linux based OS, but it was in constant change that kept breaking my system.)
